void setup() {
pinMode(2,OUTPUT);
pinMode(3,OUTPUT);
pinMode(4,OUTPUT);
pinMode(5,OUTPUT);
pinMode(6,OUTPUT);
pinMode(7,OUTPUT);
pinMode(8,OUTPUT);
pinMode(9,OUTPUT);
pinMode(10,OUTPUT);
pinMode(11,OUTPUT);
pinMode(13,OUTPUT);
}
void loop() {
 digitalWrite(11,HIGH);
  //0
digitalWrite(3,LOW);
digitalWrite(7,LOW);
digitalWrite(6,LOW);
digitalWrite(9,LOW);
digitalWrite(5,LOW);
digitalWrite(4,LOW);
delay(1000);
//1
digitalWrite(6,HIGH);
digitalWrite(9,HIGH);
digitalWrite(5,HIGH);
digitalWrite(4,HIGH);
digitalWrite(3,LOW);
digitalWrite(7,LOW);
delay(1000);
//2

digitalWrite(6,LOW);
digitalWrite(9,HIGH);
digitalWrite(5,LOW);
digitalWrite(4,LOW);
digitalWrite(3,HIGH);
digitalWrite(7,LOW);
delay(1000);
//3
digitalWrite(6,LOW);
digitalWrite(9,HIGH);
digitalWrite(5,HIGH);
digitalWrite(4,LOW);
digitalWrite(3,LOW);
digitalWrite(7,LOW);
delay(1000);
//4
digitalWrite(6,HIGH);
digitalWrite(9,LOW);
digitalWrite(5,HIGH);
digitalWrite(4,HIGH);
digitalWrite(3,LOW);
digitalWrite(7,LOW);
delay(1000);
//5
digitalWrite(6,LOW);
digitalWrite(9,LOW);
digitalWrite(5,HIGH);
digitalWrite(4,LOW);
digitalWrite(3,LOW);
digitalWrite(7,HIGH);
delay(1000);
//6
digitalWrite(6,LOW);
digitalWrite(9,LOW);
digitalWrite(5,LOW);
digitalWrite(4,LOW);
digitalWrite(3,LOW);
digitalWrite(7,HIGH);
delay(1000);
//7
digitalWrite(6,LOW);
digitalWrite(9,HIGH);
digitalWrite(5,HIGH);
digitalWrite(4,HIGH);
digitalWrite(3,LOW);
digitalWrite(7,LOW);
delay(1000);
//8
digitalWrite(6,LOW);
digitalWrite(9,LOW);
digitalWrite(5,LOW);
digitalWrite(4,LOW);
digitalWrite(3,LOW);
digitalWrite(7,LOW);
delay(1000);
//9
digitalWrite(6,LOW);
digitalWrite(9,LOW);
digitalWrite(5,HIGH);
digitalWrite(4,LOW);
digitalWrite(3,LOW);
digitalWrite(7,LOW);
delay(1000);
digitalWrite(11,LOW); 
digitalWrite(13,HIGH);
//0
digitalWrite(3,LOW);
digitalWrite(7,LOW);
digitalWrite(6,LOW);
digitalWrite(9,LOW);
digitalWrite(5,LOW);
digitalWrite(4,LOW);
delay(1000);
//1
digitalWrite(6,HIGH);
digitalWrite(9,HIGH);
digitalWrite(5,HIGH);
digitalWrite(4,HIGH);
digitalWrite(3,LOW);
digitalWrite(7,LOW);
delay(1000);
//2

digitalWrite(6,LOW);
digitalWrite(9,HIGH);
digitalWrite(5,LOW);
digitalWrite(4,LOW);
digitalWrite(3,HIGH);
digitalWrite(7,LOW);
delay(1000);
digitalWrite(13,LOW); 
digitalWrite(10,HIGH); 
  //0
digitalWrite(3,LOW);
digitalWrite(7,LOW);
digitalWrite(6,LOW);
digitalWrite(9,LOW);
digitalWrite(5,LOW);
digitalWrite(4,LOW);
delay(1000);
//1
digitalWrite(6,HIGH);
digitalWrite(9,HIGH);
digitalWrite(5,HIGH);
digitalWrite(4,HIGH);
digitalWrite(3,LOW);
digitalWrite(7,LOW);
delay(1000);
//2

digitalWrite(6,LOW);
digitalWrite(9,HIGH);
digitalWrite(5,LOW);
digitalWrite(4,LOW);
digitalWrite(3,HIGH);
digitalWrite(7,LOW);
delay(1000);
//3
digitalWrite(6,LOW);
digitalWrite(9,HIGH);
digitalWrite(5,HIGH);
digitalWrite(4,LOW);
digitalWrite(3,LOW);
digitalWrite(7,LOW);
delay(1000);
//4
digitalWrite(6,HIGH);
digitalWrite(9,LOW);
digitalWrite(5,HIGH);
digitalWrite(4,HIGH);
digitalWrite(3,LOW);
digitalWrite(7,LOW);
delay(1000);
//5
digitalWrite(6,LOW);
digitalWrite(9,LOW);
digitalWrite(5,HIGH);
digitalWrite(4,LOW);
digitalWrite(3,LOW);
digitalWrite(7,HIGH);
delay(1000);
//6
digitalWrite(6,LOW);
digitalWrite(9,LOW);
digitalWrite(5,LOW);
digitalWrite(4,LOW);
digitalWrite(3,LOW);
digitalWrite(7,HIGH);
delay(1000);
//7
digitalWrite(6,LOW);
digitalWrite(9,HIGH);
digitalWrite(5,HIGH);
digitalWrite(4,HIGH);
digitalWrite(3,LOW);
digitalWrite(7,LOW);
delay(1000);
//8
digitalWrite(6,LOW);
digitalWrite(9,LOW);
digitalWrite(5,LOW);
digitalWrite(4,LOW);
digitalWrite(3,LOW);
digitalWrite(7,LOW);
delay(1000);
//9
digitalWrite(6,LOW);
digitalWrite(9,LOW);
digitalWrite(5,HIGH);
digitalWrite(4,LOW);
digitalWrite(3,LOW);
digitalWrite(7,LOW);
delay(1000);
digitalWrite(10,LOW); 
digitalWrite(13,HIGH); 
//0
digitalWrite(3,LOW);
digitalWrite(7,LOW);
digitalWrite(6,LOW);
digitalWrite(9,LOW);
digitalWrite(5,LOW);
digitalWrite(4,LOW);
delay(1000);
//1
digitalWrite(6,HIGH);
digitalWrite(9,HIGH);
digitalWrite(5,HIGH);
digitalWrite(4,HIGH);
digitalWrite(3,LOW);
digitalWrite(7,LOW);
delay(1000);
//2

digitalWrite(6,LOW);
digitalWrite(9,HIGH);
digitalWrite(5,LOW);
digitalWrite(4,LOW);
digitalWrite(3,HIGH);
digitalWrite(7,LOW);
delay(1000);
digitalWrite(13,LOW); 
}
